name: Open PR

on:
  schedule:
    - cron: 0 0 1 */3 *

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: git checkout -b @gha/$(date +"%d-%m-%y")

      - name: Generate types.ts file
        run: ./generate.sh

      - run: npm version minor -f
      
      - name: Create PR
        run: gh pr create --label automated --draft --title "Update $(date +'%d/%m/%y')" --body "" > pr-number.txt

      - name: Close outdated PRs
        run: gh pr list --label automated --draft=false --json number --jq '.[].number' | xargs gh pr close -d -c "Superseded by #$(cat pr-number.txt)" "{}"

      - run: gh pr ready $(cat pr-number.txt)
